// This file is auto-generated by scripts/generate-giveaway-sprite-specs.mjs.
// Run `npm run sprites:generate` after replacing giveaway sprite assets.

export type GeneratedSceneSpriteBounds = {
  left: number;
  top: number;
  right: number;
  bottom: number;
};

export const CHEST_SPRITE_GEOMETRY = {
  closed: {
    frameWidth: 48,
    frameHeight: 32,
    bounds: {
      left: 2,
      top: 12,
      right: 29,
      bottom: 31
    }
  },
  selected: {
    frameWidth: 48,
    frameHeight: 32,
    bounds: {
      left: 2,
      top: 2,
      right: 29,
      bottom: 31
    }
  },
  opening: {
    frameWidth: 48,
    frameHeight: 32,
    frameBounds: [
      {
        left: 2,
        top: 12,
        right: 29,
        bottom: 31
      },
      {
        left: 2,
        top: 12,
        right: 29,
        bottom: 31
      },
      {
        left: 1,
        top: 13,
        right: 29,
        bottom: 31
      },
      {
        left: 1,
        top: 13,
        right: 29,
        bottom: 31
      },
      {
        left: 2,
        top: 11,
        right: 29,
        bottom: 31
      },
      {
        left: 2,
        top: 11,
        right: 30,
        bottom: 31
      },
      {
        left: 2,
        top: 9,
        right: 31,
        bottom: 31
      },
      {
        left: 2,
        top: 23,
        right: 41,
        bottom: 31
      },
      {
        left: 2,
        top: 21,
        right: 40,
        bottom: 31
      },
      {
        left: 2,
        top: 21,
        right: 40,
        bottom: 31
      }
    ],
    finalBounds: {
      left: 2,
      top: 21,
      right: 40,
      bottom: 31
    }
  },
  winnerOpening: {
    frameWidth: 48,
    frameHeight: 32,
    frameBounds: [
      {
        left: 2,
        top: 12,
        right: 29,
        bottom: 31
      },
      {
        left: 2,
        top: 12,
        right: 29,
        bottom: 31
      },
      {
        left: 1,
        top: 13,
        right: 29,
        bottom: 31
      },
      {
        left: 1,
        top: 13,
        right: 29,
        bottom: 31
      },
      {
        left: 2,
        top: 11,
        right: 29,
        bottom: 31
      },
      {
        left: 2,
        top: 11,
        right: 30,
        bottom: 31
      },
      {
        left: 2,
        top: 9,
        right: 31,
        bottom: 31
      },
      {
        left: 2,
        top: 13,
        right: 41,
        bottom: 31
      },
      {
        left: 2,
        top: 5,
        right: 40,
        bottom: 31
      },
      {
        left: 2,
        top: 1,
        right: 40,
        bottom: 31
      }
    ],
    finalBounds: {
      left: 2,
      top: 1,
      right: 40,
      bottom: 31
    }
  },
  openingMask: {
    frameWidth: 48,
    frameHeight: 32,
    bounds: {
      left: 5,
      top: 12,
      right: 28,
      bottom: 30
    },
    frameBounds: [
      {
        left: 5,
        top: 12,
        right: 28,
        bottom: 30
      },
      {
        left: 5,
        top: 12,
        right: 28,
        bottom: 30
      },
      {
        left: 4,
        top: 13,
        right: 28,
        bottom: 30
      },
      {
        left: 4,
        top: 13,
        right: 28,
        bottom: 30
      },
      {
        left: 5,
        top: 12,
        right: 28,
        bottom: 30
      },
      {
        left: 6,
        top: 11,
        right: 29,
        bottom: 30
      },
      {
        left: 6,
        top: 9,
        right: 30,
        bottom: 30
      },
      {
        left: 6,
        top: 23,
        right: 40,
        bottom: 30
      },
      {
        left: 6,
        top: 21,
        right: 39,
        bottom: 30
      },
      {
        left: 6,
        top: 21,
        right: 39,
        bottom: 30
      }
    ],
    finalBounds: {
      left: 6,
      top: 21,
      right: 39,
      bottom: 30
    }
  }
} as const;
